homePage updated
M2htechnologies/event_managment_web pull request #4
Opened 2024-08-19 14:23 UTC by raffay0shahzad

Kindly Review the PR for homePage

2024-08-19 18:05 UTC, ShanCoder110 requested changes

2024-08-19 18:05 UTC, ShanCoder110 commented on client/src/pages/CreateEventPage/index.jsx
> +                    setFieldValue("eventImage", event.currentTarget.files[0]);
Move this function declaration above return just call it here

2024-08-19 18:05 UTC, ShanCoder110 commented on client/src/pages/CreateEventPage/index.jsx
> +EventForm.propTypes = {
What is this doing?

2024-08-19 18:05 UTC, ShanCoder110 commented on client/src/pages/LoginPage/Form.jsx
>    name: yup.string().required("required"),
Make separate file

2024-08-19 18:05 UTC, ShanCoder110 commented on client/src/pages/LoginPage/Form.jsx
> +        "http://localhost:3001/auth/register",
Same as above

2024-08-19 18:05 UTC, ShanCoder110 commented on client/src/pages/LoginPage/Form.jsx
> +          headers: {
Add headers in config file

2024-08-19 18:05 UTC, ShanCoder110 commented on client/src/pages/LoginPage/Form.jsx
> +        values,
Move to constant and config also move base url to env

2024-08-19 18:05 UTC, ShanCoder110 commented on client/src/pages/LoginPage/Form.jsx
> +                    setPageType(isLogin ? "register" : "login");
Move function before return call it here

2024-08-19 18:05 UTC, ShanCoder110 commented on client/src/state/index.jsx
> +      state.token = action.payload.token;
Store token in local storage

2024-08-19 19:10 UTC, raffay0shahzad commented on client/src/pages/CreateEventPage/index.jsx
> +EventForm.propTypes = {
It was giving some about not passing the props for Event form so looked it up on the internet

2024-08-20 07:39 UTC, ShanCoder110 commented on client/src/App.jsx
> +//import Cart from "./pages/CartPage";
remove commented code

2024-08-20 07:39 UTC, ShanCoder110 commented on client/src/App.jsx
> +          {/* <Route path={CART_ROUTE} element={<Cart />} /> */}
remove commented code

2024-08-20 07:40 UTC, ShanCoder110 commented on client/src/ValidationSchemas/index.js
> +
move schemas in different files

2024-08-20 07:40 UTC, ShanCoder110 commented on client/src/axiosConfig.js
> +  };
eol missing

2024-08-20 07:40 UTC, ShanCoder110 commented on client/src/ValidationSchemas/index.js
> +    password: Yup.string().required("required"),
eol missing

2024-08-20 07:40 UTC, ShanCoder110 commented on client/src/components/Events.jsx
> +//import axios from "axios";
remove commented code

2024-08-20 07:40 UTC, ShanCoder110 commented on client/src/pages/CreateEventPage/index.jsx
> +//import React from 'react';
remove commented code

2024-08-20 07:43 UTC, ShanCoder110 requested changes
minor comments added

2024-08-20 07:43 UTC, ShanCoder110 commented on client/src/components/Events.jsx
> +        const response = await axiosInstance.get(GET_EVENTS);
for GET_EVENT be more specific like GET_EVENT_API_ROUTE or EVENT_API_ROUTE.getAllEvents

2024-08-20 08:08 UTC, ShanCoder110 approved these changes

2024-08-20 08:08 UTC, merged